export default [
    {
        email: "aaron_barcelita@dlsu.edu.ph",
        password: "12345678",
        fname: "Aaron",
        lname: "Barcelita",
        mname: "Chucas",
        role: "Technician",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/war_cat.jpeg",
        description: "",
    },
    {
        email: "john_mendoza@dlsu.edu.ph",
        password: "12345678",
        fname: "John Kirbie",
        lname: "Mendoza",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/john_profile.png",
        description: "",
    },
    {
        email: "josh_cariaga@dlsu.edu.ph",
        password: "12345678",
        fname: "Josh Enrico",
        lname: "Cariaga",
        role: "Technician",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/catorang.png",
        description: "Testing",
    },
    {
        email: "aaron_daniel_go@dlsu.edu.ph",
        password: "12345678",
        fname: "Aaron Daniel",
        lname: "Go",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/fauna_pfp.jpeg",
        description: "",
    },
    {
        email: "teto_kasane@dlsu.edu.ph",
        password: "12345678",
        fname: "Teto",
        lname: "Kasane",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/teto_kasane_pfp.png",
        description: "",
    },
];
