export default [
    {
        user_id: 1,
        email: "aaron_barcelita@dlsu.edu.ph",
        password: "12345678",
        fname: "Aaron",
        lname: "Barcelita",
        mname: "Chucas",
        role: "Admin",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/war_cat.jpeg",
        description: "",
    },
    {
        user_id: 2,
        email: "john_mendoza@dlsu.edu.ph",
        password: "12345678",
        fname: "John Kirbie",
        lname: "Mendoza",
        role: "Technician",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/john_profile.png",
        description: "",
    },
    {
        user_id: 3,
        email: "josh_cariaga@dlsu.edu.ph",
        password: "12345678",
        fname: "Josh Enrico",
        lname: "Cariaga",
        role: "Technician",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/catorang.png",
        description: "Testing",
    },
    {
        user_id: 4,
        email: "aaron_daniel_go@dlsu.edu.ph",
        password: "12345678",
        fname: "Aaron Daniel",
        lname: "Go",
        role: "Technician",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/furina_pfp.jpeg",
        description: "",
    },
    {
        user_id: 5,
        email: "teto_kasane@dlsu.edu.ph",
        password: "12345678",
        fname: "Teto",
        lname: "Kasane",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/teto_kasane_pfp.jpg",
        description: "",
    },
    {
        user_id: 6,
        email: "hatsune_miku@dlsu.edu.ph",
        password: "12345678",
        fname: "Hatsune",
        lname: "Miku",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/miku_pfp.png",
        description: "Miku, Miku, you can call me Miku. Blue hair, blue tie, hiding in your Wi-Fi!",
    },
    {
        user_id: 7,
        email: "akita_neru@dlsu.edu.ph",
        password: "12345678",
        fname: "Akita",
        lname: "Neru",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/neru_pfp.png",
        description: "",
    },
    {
        user_id: 8,
        email: "haru_urara@dlsu.edu.ph",
        password: "12345678",
        fname: "Haru",
        lname: "Urara",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/haru_urara_pfp.png",
        description: "0 wins, 100% heart.",
    },
    {
        user_id: 9,
        email: "hitori_gotoh@dlsu.edu.ph",
        password: "12345678",
        fname: "Hitori",
        lname: "Gotoh",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/bocchi_pfp.png",
        description: "I should really change the way I am...",
    },
    {
        user_id: 10,
        email: "kita_ikuyo@dlsu.edu.ph",
        password: "12345678",
        fname: "Kita",
        lname: "Ikuyo",
        role: "Student",
        status: "Active",
        profile_pic_path: "/uploads/profile_pictures/kita_ikuyo_pfp.png",
        description: "Radiates sunshine.",
    },
];
